### ISSUE TITLE
`TreadSanitizer` typo in Chapter 3.1 footnote 12

### ISSUE THREAD

**Issue by Michcioperz** [tnballo/high-assurance-rust#1]
In the 12th footnote in currently published version of https://highassurance.rs/chp3/undef.html the link to ThreadSanitizer has a typo

**Comment by tnballo** [comment]
Good catch, thank you! Fixed and updated the site.

**Comment by tnballo** [comment]
@Michcioperz Wanted to let you know that I've started a [Community Contributors](https://highassurance.rs/chp1/about_the_team.html#community-contributors) list and added you!

Source for the book is now in this repo, if you find another typo in the future feel free to [submit a PR](https://github.com/tnballo/high-assurance-rust/blob/main/CONTRIBUTING.md).
