### ISSUE TITLE
Chapter 2 Dynamic Assurance lib.rs path

### ISSUE THREAD

**Issue by aelnona** [tnballo/high-assurance-rust#16]
In [dynamic_assurance_2.md](https://github.com/tnballo/high-assurance-rust/blob/main/src/chp2/dynamic_assurance_2.md) and [dynamic_assurance_3.md](https://github.com/tnballo/high-assurance-rust/blob/main/src/chp2/dynamic_assurance_3.md), the path to rc4's `lib.rs` is written as `crypto_tool/rc4/lib.rs`, though `cargo new crypto_tool/rc4 --lib` creates lib.rs in `crypto_tool/rc4/src/lib.rs`

**Comment by aelnona** [comment]
My mistake, I missed the first line of code

**Comment by tnballo** [comment]
You're right, this is a mistake - both `.md` files should definitely have `crypto_tool/rc4/src/lib.rs`. `cargo` always creates the `src` directory, and that's the correct path [in this repo](https://github.com/tnballo/high-assurance-rust/blob/main/code_snippets/chp2/crypto_tool/rc4/src/lib.rs). Sorry for the confusion!

Would you like to PR a fix for this issue?

**Comment by aelnona** [comment]
Sure, will do
