### ISSUE TITLE
PDF Version

### ISSUE THREAD

**Issue by shirshak55** [tnballo/high-assurance-rust#2]
I have added pdf version of high assurance rust in https://github.com/shirshak55/Rust-Book-In-PDF/releases. Let me know if there is any issue.

**Comment by tnballo** [comment]
No problem! It's a free book, you’re more than welcome to host a copy in your repository.

I will be adding PDF and EPUB downloads to the "official" site as well. Several people have requested these formats, and that will allow me to keep them up to date in a central location (so there's one place to always grab the latest).

PS - a helpful person also let me know the EPUB for any hosted mdbook can be exported via:

https://github.com/rust-lang/rust/issues/20866#issuecomment-495962961

**Comment by shirshak55** [comment]
@tnballo yea the only issue with that approach is automation is hard. I will need to patch the chromium browser.
