### ISSUE TITLE
Chapter 1.5 namespaces reference link.

### ISSUE THREAD

**Issue by jamesreprise** [tnballo/high-assurance-rust#21]
In [src/chp1/_hands_on.md](https://github.com/tnballo/high-assurance-rust/blob/main/src/chp1/_hands_on.md), line 109:
```
[^Namespaces]: [*Everything You Need to Know about Linux Containers, Part II: Working with Linux Containers (LXC)*](https://code.visualstudio.com/docs/remote/containers). Petros Koutoupis (2018).
```
should be
```
[^Namespaces]: [*Everything You Need to Know about Linux Containers, Part II: Working with Linux Containers (LXC)*](https://www.linuxjournal.com/content/everything-you-need-know-about-linux-containers-part-ii-working-linux-containers-lxc). Petros Koutoupis (2018).
```

The original link is about containers, but about setting them up using an extension for VScode and doesn't have the given title.

**Comment by tnballo** [comment]
Great catch, must have copy/pasted the wrong link - thanks for finding the right one!

Would you like to PR the fix per [`CONTRIBUTING.md`](https://github.com/tnballo/high-assurance-rust/blob/main/CONTRIBUTING.md)?

**Comment by jamesreprise** [comment]
I would! Let me know if that looks correct.

Many thanks for all the work so far, I hope you'll continue.

**Comment by tnballo** [comment]
Thank you, glad you like it!

For sure - chapter 4 is currently in the works (private repo b/c I'm not bold enough to write drafts in the open), challenging one content-wise but also excited to see it come together :blush:
