### ISSUE TITLE
Incorrect wording in chapter 1.1 "Languages by Level"

### ISSUE THREAD

**Issue by kaylynn234** [tnballo/high-assurance-rust#3]
In the second sentence of this section, the book currently reads as
> Rust can run in levels of the stack **were** scripting languages

... but the usage of "were" is incorrect. It should instead be
> Rust can run in levels of the stack **where** scripting languages

As a side note, I would really appreciate if the book's source was present in this repository, even if you decide to keep it in some other branch for now - needing to open an issue or send an email is a bit irritating when one could instead just open a pull request to address an issue directly.

**Comment by tnballo** [comment]
Thanks, fixed and pushed!

You're right, that'd be a smoother workflow. Reducing friction to contribution will result in a better book in the long term. Thanks for suggesting this.

I currently have it in a repo with a lot of rough-draft/in-progress writing for later chapters that you really don't want to see (trust me :sweat_smile:). So I'll split that out and add the full source for what is currently public to this repo in the coming days. That should allow easier fixes for the current content.

I'm not personally comfortable with writing fully in the open, but I can port in new content from the private dev repo every time it's ready to be public!

**Comment by tnballo** [comment]
@kaylynn234 Wanted to let you know that I've started a [Community Contributors](https://highassurance.rs/chp1/about_the_team.html#community-contributors) list and added you!

Source for the book is now in this repo, if you find another typo in the future feel free to [submit a PR](https://github.com/tnballo/high-assurance-rust/blob/main/CONTRIBUTING.md).
