### ISSUE TITLE
dead?

### ISSUE THREAD

**Issue by Ragarnoy** [tnballo/high-assurance-rust#36]
is this project dead?

**Comment by qrilka** [comment]
There's also the same question at https://github.com/tnballo/high-assurance-rust/discussions/35

**Comment by tnballo** [comment]
Hey! Definitely not dead, but have not been making consistent progress as of late. Please see the mentioned thread #35 for a more [detailed reply](https://github.com/tnballo/high-assurance-rust/discussions/35#discussioncomment-5732072).

Closing this issue in favor of centralizing on the thread.

Appreciate your interest in this project!
