### ISSUE TITLE
E: Unable to locate package rr

### ISSUE THREAD

**Issue by rrevi** [tnballo/high-assurance-rust#5]
When running `docker build .` on the Dockerfile, the following errors occurs:

<img width="1512" alt="Screen Shot 2022-03-30 at 5 10 01 AM" src="https://user-images.githubusercontent.com/1561054/160796111-e29bc970-beff-4647-8d95-f3bf721b9091.png">

Just wondering if anyone else has run or is running into this issue?

**Comment by tnballo** [comment]
Thank you so much for reporting this! Ironing out container support is important.

Although I can't replicate the issue locally (the irony isn't lost on me :wink:), I'm certain if you hit it then others will too.

Pushed what might be a fix in `7af85dbb`, just now. Please let me know if the issue persists.

**Comment by rrevi** [comment]
> Thank you so much for reporting this! Ironing out container support is important.
> 
> Although I can't replicate the issue locally (the irony isn't lost on me 😉), I'm certain if you hit it then others will too.
> 
> Pushed what might be a fix in `7af85dbb`, just now. Please let me know if the issue persists.

Thanks for the prompt reply!

It's rather strange that you aren't hitting this issue, I wonder if it's because I am on Docker on Apple Silicon? (not that this makes a whole lot of sense).

And yes, despite your attempt at a fix, the issue persists 😞

**Comment by duzumaki** [comment]
@rrevi `rust:1.59-slim` is an x86 image. You want `arm64v8/rust:1.59-slim` for apple silicon

**Comment by rrevi** [comment]
> @rrevi `rust:1.59-slim` is an x86 image. You want `arm64v8/rust:1.59-slim` for apple silicon

That makes a lot of sense, thanks @duzumaki

**Comment by tnballo** [comment]
Interesting, would not have guessed! Thanks for the save @duzumaki.

I don't anticipate any problems on Apple/aarch64 platforms for the currently available content/exercises, but some of the [planned tools](https://highassurance.rs/chp16_appendix/tools.html) may not yet have support. Noted as something to investigate and possibly CI in the future.

**Comment by tnballo** [comment]
@rrevi and @duzumaki - Wanted to let you know that I've started a [Community Contributors](https://highassurance.rs/chp1/about_the_team.html#community-contributors) list and added you!

There's now an [aarch64-specific `Dockerfile`](https://github.com/tnballo/high-assurance-rust/blob/main/docker_aarch64/Dockerfile) that unfortunately doesn't include `rr` (this tool [requires x86](https://github.com/rr-debugger/rr#system-requirements) hardware support).

Source for the book is now in this repo so feel free to [submit a PR](https://github.com/tnballo/high-assurance-rust/blob/main/CONTRIBUTING.md) for future updates.
