### ISSUE TITLE
"Heartbleed" misspelled as "Heart Bleed"

### ISSUE THREAD

**Issue by LoganDark** [tnballo/high-assurance-rust#6]
https://highassurance.rs/chp1/_index.html

Public content is not published yet (I have seen #4) so I can't open a PR for it, sorry :(

**Comment by tnballo** [comment]
Should be good to go! Source for the book is now in this repo, and there is a [`CONTRIBUTING.md`](https://github.com/tnballo/high-assurance-rust/blob/main/CONTRIBUTING.md).
